"""init_db

Revision ID: 87cce62d3a0e
Revises: 
Create Date: 2024-11-22 17:39:55.171742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87cce62d3a0e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_link', sa.String(length=64), nullable=False),
    sa.Column('chat_name', sa.String(length=128), nullable=False),
    sa.Column('chat_type', sa.Enum('CHAT', 'CHANNEL', name='type_chat'), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_index(op.f('ix_chats_chat_id'), 'chats', ['chat_id'], unique=True)
    op.create_table('proxys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=256), nullable=False),
    sa.Column('port', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('login', sa.String(length=256), nullable=False),
    sa.Column('country', sa.String(length=256), nullable=False),
    sa.Column('active_to', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proxys_id'), 'proxys', ['id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('features', sa.String(length=256), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_table('account_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.BigInteger(), nullable=False),
    sa.Column('hash_id', sa.String(length=60), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('session_name', sa.String(length=100), nullable=False),
    sa.Column('patch_to_session', sa.String(length=100), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('proxy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proxy_id'], ['proxys.id'], name='fk_proxy_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_info_id'), 'account_info', ['id'], unique=False)
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('subscribers', sa.Integer(), nullable=False),
    sa.Column('tracking_time', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscribers_id'), 'subscribers', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('login', sa.String(length=256), nullable=True),
    sa.Column('hashed_password', sa.String(length=256), server_default='', nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('scopes', sa.Enum('USER', 'ADMIN', name='rolepermissionsenum'), nullable=False),
    sa.Column('language', sa.String(length=5), server_default='ru', nullable=False),
    sa.Column('end_time_subscription', sa.DateTime(), nullable=True),
    sa.Column('current_project', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.create_table('views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('tracking_time', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_views_id'), 'views', ['id'], unique=False)
    op.create_table('account_chat_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('joined_time', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account_info.id'], name='fc_account_id_ACA'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], name='fc_chat_id_ACA'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_chat_association_id'), 'account_chat_association', ['id'], unique=False)
    op.create_table('auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_id'), 'auth', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_name', sa.String(length=128), nullable=False),
    sa.Column('creation_date', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('description_text', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('invoices_pending_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('chat_link', sa.String(length=256), nullable=False),
    sa.Column('chat_name', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_pending_chat_id'), 'invoices_pending_chat', ['id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=4096), nullable=True),
    sa.Column('creation_date', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('was_changed', sa.Enum('NOT_CHANGED', 'EDITED', 'DELETED', name='poststatusenum'), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fc_custom_post_project_id', ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_table('project_сhat_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('auto_post', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('creation_date', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('pinned', sa.Boolean(), server_default='0', nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], name='fc_project_chat_association_CHAT_ID', ondelete='cascade'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fc_project_chat_association_PROJECT_ID', ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_сhat_associations_id'), 'project_сhat_associations', ['id'], unique=False)
    op.create_table('medias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('file_url', sa.String(length=256), nullable=False),
    sa.Column('file_type', sa.Enum('PHOTO', 'VIDEO', 'AUDIO', 'DOCUMENT', name='mediatypeenum'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medias_id'), 'medias', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medias_id'), table_name='medias')
    op.drop_table('medias')
    op.drop_index(op.f('ix_project_сhat_associations_id'), table_name='project_сhat_associations')
    op.drop_table('project_сhat_associations')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_invoices_pending_chat_id'), table_name='invoices_pending_chat')
    op.drop_table('invoices_pending_chat')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_auth_id'), table_name='auth')
    op.drop_table('auth')
    op.drop_index(op.f('ix_account_chat_association_id'), table_name='account_chat_association')
    op.drop_table('account_chat_association')
    op.drop_index(op.f('ix_views_id'), table_name='views')
    op.drop_table('views')
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subscribers_id'), table_name='subscribers')
    op.drop_table('subscribers')
    op.drop_index(op.f('ix_account_info_id'), table_name='account_info')
    op.drop_table('account_info')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_proxys_id'), table_name='proxys')
    op.drop_table('proxys')
    op.drop_index(op.f('ix_chats_chat_id'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
